"""
The modeled subway network, loaded from the MTA's own GTFS static feed.

  475 stations · 1,096 segments · 150 walking transfers · 28 routes

`data/subway_graph.json` is generated by `scripts/build_graph.py` and committed,
so nothing here needs the network at runtime; re-run that script to refresh it.
Each segment carries a *per-line* median run time taken from weekday schedules,
which is how an express hop ends up cheaper than the local one over the same
pair of stations.

Stations are GTFS parent stations. Parent stations joined by in-system transfers
share a `complex` id — four of them make up Times Sq-42 St — so the geocoder can
treat one complex as one place while still flagging the six unrelated "86 St"s.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_DATA = Path(__file__).parent / "data" / "subway_graph.json"

_graph = json.loads(_DATA.read_text())

GTFS_SOURCE: str = _graph["source"]

# Each STATION: id, name, lat, lng, lines[], complex
STATIONS: list[dict] = _graph["stations"]

# Ride segments between adjacent stations: {"from", "to", "lines": {line: minutes}}
RIDE_EDGES: list[dict] = _graph["edges"]

# In-system walking connections: {"from", "to", "minutes"}
WALK_EDGES: list[dict] = _graph["transfers"]

# route_id -> {name, label, color, long_name}
SUBWAY_LINES: dict[str, dict] = _graph["lines"]

# ── Derived lookups (built once at import) ─────────────────────────────
STATION_BY_ID: dict[str, dict] = {s["id"]: s for s in STATIONS}
STATION_IDS: list[str] = [s["id"] for s in STATIONS]

COMPLEX_MEMBERS: dict[str, list[str]] = {}
for _s in STATIONS:
    COMPLEX_MEMBERS.setdefault(_s["complex"], []).append(_s["id"])


def _walk_components() -> dict[str, list[str]]:
    """Stations you can actually walk between inside the fare zone.

    A complex groups same-named platforms so a rider naming one gets one
    answer; this is the stricter relation — an official transfer or a
    passageway-length walk — and it is what "which lines serve this station"
    should be built from.
    """
    parent = {sid: sid for sid in STATION_IDS}

    def find(x: str) -> str:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for edge in WALK_EDGES:
        a, b = edge["from"], edge["to"]
        if a in parent and b in parent and find(a) != find(b):
            parent[find(a)] = find(b)

    groups: dict[str, list[str]] = {}
    for sid in STATION_IDS:
        groups.setdefault(find(sid), []).append(sid)
    return {sid: groups[find(sid)] for sid in STATION_IDS}


WALK_CONNECTED: dict[str, list[str]] = _walk_components()


def connected_members(station_id: str) -> list[str]:
    """Every platform walkable from this one without leaving the system."""
    return WALK_CONNECTED.get(station_id, [station_id])


def same_complex(a_id: str, b_id: str) -> bool:
    """Whether two stations are platforms of the same station complex."""
    a, b = STATION_BY_ID.get(a_id), STATION_BY_ID.get(b_id)
    return bool(a and b and a["complex"] == b["complex"])


def line_color(line_id: str) -> str:
    """Hex color for a subway line, or a neutral gray if unknown."""
    return SUBWAY_LINES.get(line_id, {}).get("color", "#6B7280")


def line_label(line_id: str) -> str:
    """Rider-facing name: "6X" is the "6 express", "GS" the "42 St Shuttle"."""
    return SUBWAY_LINES.get(line_id, {}).get("label", line_id)


@lru_cache(maxsize=64)
def feed_line(line_id: str) -> str:
    """Map a schedule route id to the line id the real-time alerts feed uses.

    The feed publishes status for the 23 rider-facing lines: express variants
    ride under their base letter/number, the three shuttles under "S".
    """
    if line_id in {"GS", "FS", "H"}:
        return "S"
    return line_id[:-1] if line_id.endswith("X") and len(line_id) > 1 else line_id
